# Generated by Django 4.2.1 on 2024-09-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Sami Elsayed', max_length=200),
        ),
    ]
